# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=20, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('module_caption', models.CharField(max_length=255, verbose_name='\u6a21\u5757\u529f\u80fd\u63cf\u8ff0')),
                ('module_extend', models.CharField(max_length=2000, verbose_name='\u6a21\u5757\u524d\u7aef\u6269\u5c55')),
            ],
        ),
        migrations.CreateModel(
            name='ServerAppCateg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_categ_name', models.CharField(max_length=30, verbose_name='\u670d\u52a1\u5e94\u7528\u5206\u7c7b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='ServerFunCateg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_categ_name', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u529f\u80fd\u5206\u7c7b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=13, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('server_wip', models.CharField(max_length=15, verbose_name='\u4e3b\u673a\u5916\u7f51ip')),
                ('server_lip', models.CharField(max_length=12, verbose_name='\u4e3b\u673a\u5185\u7f51ip')),
                ('server_op', models.CharField(max_length=10, verbose_name='\u4e3b\u673a\u64cd\u4f5c\u7cfb\u7edf')),
                ('server_app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ServerAppCateg')),
            ],
        ),
        migrations.AddField(
            model_name='serverappcateg',
            name='server_categ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ServerFunCateg'),
        ),
    ]
