# -*- coding: utf-8 -*-

MEMBER_STATUS_NORMAL = 1
MEMBER_STATUS_UNORMAL = 2

MEMBER_STATUS_LIST = [MEMBER_STATUS_NORMAL, MEMBER_STATUS_UNORMAL]

MALE = 1
FEMALE = 2
OTHER = 3
SEX_LIST = [MALE, FEMALE, OTHER]


ADDRESS_STATUS_NORMAL = 1
ADDRESS_STATUS_DELETE = 2

MEMBER_STATUS_LIST = [ADDRESS_STATUS_NORMAL, ADDRESS_STATUS_DELETE]

COMMENT_STATUS_NORMAL = 1
COMMENT_STATUS_DELETE = 2

COMMENT_STATUS_LIST = [COMMENT_STATUS_NORMAL, COMMENT_STATUS_DELETE]
