#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url


urlpatterns = [
    url(r'^login/', 'app01.views.login'), #url为login，调用app01的views.py文件下的login函数来实现
    url(r'^index/', 'app01.views.index'),
    url(r'^user/', 'app01.views.user'),
    url(r'^usergroup/', 'app01.views.usergroup'),
    url(r'^host/', 'app01.views.host'),
]

