FOODTYPE_STATUS_NORMAL = 1
FOODTYPE_STATUS_DELETED = 2


FOOD_STATUS_NORMAL = 1
FOOD_STATUS_DELETED = 2


ORDER_STATUS_CREATE = 1
ORDER_STATUS_CONFIRM = 2
ORDER_STATUS_PAID = 3
ORDER_STATUS_CANCEL = 4
ORDER_STATUS_OUTDATE = 5
ORDER_STATUS_DELETE = 6


ORDER_STATUS_LIST = [ORDER_STATUS_CREATE, ORDER_STATUS_CONFIRM, ORDER_STATUS_PAID, ORDER_STATUS_CANCEL, ORDER_STATUS_OUTDATE, ORDER_STATUS_DELETE]
